### ISSUE TITLE
Impl Clone, PartialEq, Eq for Markup?

### ISSUE THREAD

**Issue by LukasKalbertodt** [lfairy/maud#100]
Should be possible since it's just a string. Are there any reasons not to derive those traits?

**Comment by lfairy** [comment]
I agree with `Clone`, and would be happy to take a PR that adds `#[derive(Copy, Clone)]`.

Not sure about `PartialEq` though. Semantically, a `Markup` object represents an HTML fragment, so it would also make sense to compare parse trees instead (e.g. `PreEscaped("<br>") == PreEscaped("<br >")`). Best to avoid this ambiguity and not implement the comparison traits.

**Comment by LukasKalbertodt** [comment]
@lfairy Yeah, I guess you're right about `Eq` :)
