### ISSUE TITLE
Idea: arbitrary inline expresion

### ISSUE THREAD

**Issue by dpc** [lfairy/maud#11]
I'm thinking, it would be nice to be able to put any random rust expression inside `html!`

Eg:

```
html! {
  p {
     $(match id  {
        Some(id) => id,
        None => 0,
      })
   }
}
```

This could replace `$if` `$else` etc. It seems it is more flexible to just get whole `$( ... )` block and stuff it into lambda, rather then having only some types of expressions supported.

Is this already possible? Did I missed anything in the docs?

**Comment by dpc** [comment]
Also, I'm having problems with inline expressions inside attributes.

What I want:

```
script src=$ASSETS_PATH/"js/epiceditor.min.js" {}
```

is not working.

**Comment by dpc** [comment]
```
${ }
```
is what I was looking for, I guess.

**Comment by lfairy** [comment]
Your original example works already, since `match { .. }` is a valid Rust expression.
