### ISSUE TITLE
Cannot assignment in macro.

### ISSUE THREAD

**Issue by sackery** [lfairy/maud#113]

**Comment by bb010g** [comment]
Could you provide a minimal example that exhibits this behavior?

**Comment by sackery** [comment]
@while xx < 100 && xx <= 10 {
//xx += 1
}

**Comment by sackery** [comment]
```
@while xx < 100 && xx <= 10 {
//xx += 1
}
```

**Comment by lfairy** [comment]
Do you have a practical use case for this feature?

Allowing arbitrary Rust statements in templates smells like mixing logic and presentation to me, which is something I don't want to encourage.
