### ISSUE TITLE
Any way to exclude html and body tags from markup?

### ISSUE THREAD

**Issue by madmaxio** [lfairy/maud#118]
I plan to use some custom markup pieces on demand, for dynamic content. Any way to force html! macro to generate markup without html and body tags?

**Comment by lfairy** [comment]
If I understand correctly, Maud already does this. For example, the [tests](https://github.com/lfairy/maud/blob/master/maud/tests/basic_syntax.rs) don't involve body tags at all.

**Comment by madmaxio** [comment]
Well, true ^^, if so, how Maud decides to add or not to add html and body tags to markup?

**Comment by lfairy** [comment]
It only adds them if you write them in yourself 😛

`html! { p { "Hello" } }` will evaluate to just `<p>Hello</p>`.

`html! { body { p { "Hello" } } }` will evaluate to `<body><p>Hello</p></body>`.

There's really nothing special going on.

**Comment by madmaxio** [comment]
Okay, thx,
