### ISSUE TITLE
Expressions inside tag attributes.

### ISSUE THREAD

**Issue by dpc** [lfairy/maud#12]
I'm having problems with inline expressions inside attributes.

What I want:
```
script src=$ASSETS_PATH/"js/epiceditor.min.js" {}
```
is not working.

**Comment by lfairy** [comment]
Group the values in a `{}` block:

    script src={ $ASSETS_PATH "/js/epiceditor.min.js" } {}

I've updated the book with this solution. It's been supported for a while now, albeit undocumented.
