### ISSUE TITLE
not compiling

### ISSUE THREAD

**Issue by gurugeek** [lfairy/maud#120]
I think it needs an update to the latest version of literal text? the old doesn't compile. 

cargo run
   Compiling literalext v0.1.1
error[E0554]: #![feature] may not be used on the stable release channel
  --> /Users/doctorstrange/.cargo/registry/src/github.com-1ecc6299db9ec823/literalext-0.1.1/src/lib.rs:19:37
   |
19 | #![cfg_attr(feature = "proc-macro", feature(proc_macro))]
   |                                     ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `literalext`.

To learn more, run the command again with --verbose.

**Comment by lfairy** [comment]
It looks like you're using the stable version of the compiler? Maud only supports the Nightly version of Rust, so you need to use that instead.

You're right that we need to upgrade literalext, but the old version should still work.
