### ISSUE TITLE
Build error on nightly (2018-04-05)

### ISSUE THREAD

**Issue by anxiousmodernman** [lfairy/maud#121]
I'm doing a release build with `rocket` features. I get a big run of errors when compiling `maud_macros`. This is a pretty recent development, so I don't think it's due to any code change in maud itself.

![proc](https://user-images.githubusercontent.com/396004/38401710-32c31d7c-390c-11e8-8223-fcf64cbe6ad4.png)

_many other errors not shown_

[These are the most recent docs](https://doc.rust-lang.org/nightly/proc_macro/) I can find for the `proc_macro` crate. It looks like major changes to the API.

**Comment by lfairy** [comment]
Thanks for reporting. I'll look into it over the coming weekend. (Unless you'd like to do the upgrade instead 😉)

**Comment by anxiousmodernman** [comment]
I'll give it a shot and take some notes here.

It looks like a `TokenTree` is now an enum, not a struct, and so we express different token types as enum variants. Converting the struct syntax to the new enum shouldn't be so bad. 

Not sure about an equivalent to `TokenTreeIter` yet. I think they want us to deal with a `TokenStream` directly, [it has an `IntoIterator` impl](https://doc.rust-lang.org/nightly/proc_macro/struct.TokenStream.html#implementations).

**Comment by anxiousmodernman** [comment]
Worked through `markup` and `markups`. So far I'm just letting complaints from my IDE (thanks RLS!) be my guide, until we are actually compiling under the new types. Then we can address correctness. Flagging this in the meantime: https://github.com/anxiousmodernman/maud/commit/4cd5451cec60797e0e2425235a355791442c8dfb#diff-285844f0c3c48a3b23fa1b5ec1140722R166

A `TokenTree::Group(x)` holds a `Group` that has a `stream() -> TokenStream` method, but the yielded stream is the tokens without the specified delimiter. I'll keep going and assume this is what we want, but I'm actually not sure.

**Comment by anxiousmodernman** [comment]
A `TokenStream` can be built from an iterator of `TokenTree`. My idea is to change the signature of `match_arm` to support this. It yields a funky from_iter/into_iter dance, and look like the internals of `match_arm` will need some rework. 
![match_arms](https://user-images.githubusercontent.com/396004/38476826-abf1020e-3b64-11e8-8a24-c45c9efc844a.png)

**Comment by anxiousmodernman** [comment]
This might be fixed. Interested parties can try testing with my fork:

```toml
# in Cargo.toml
[dependencies]
maud = { git = "https://github.com/anxiousmodernman/maud.git", branch = "121_proc_macro", features = ["rocket"] }
```
Of course, you will need to list the particular features your project depends on.

**Comment by anxiousmodernman** [comment]
I'll leave my fork up for a while, but these changes are now in maud master.
