### ISSUE TITLE
Suggestion: Run-time evaluated attributes.

### ISSUE THREAD

**Issue by eedahl** [lfairy/maud#130]
This may be a non-issue in the current build or there could be a workaround, but I see from the [documentation](https://maud.lambda.xyz/basic_syntax.html) that attributes only accept string literals and .attr with the [] bracket. The program I'm making is primarily displaying tables, and some of the cells/rows have either on-click callbacks prescribed by class/id in JS that depend on the row number (of which there are 50+), and many of the cells have colouring depending on a class attribute (of which there are 7). Obviously, typing these all out and checking a bit for each would be rather cumbersome. From what I can tell so far this is the only thing holding this back from being the perfect templating system for my needs.

**Comment by eedahl** [comment]
Sorry, I see this is already an open issue. https://github.com/lfairy/maud/issues/128

**Comment by lfairy** [comment]
No worries. I appreciate these comments regardless, because they help me prioritize.

Are you aware of [splices in attributes](https://maud.lambda.xyz/dynamic_content.html#splices-in-attributes)? Now that I mention it, I should probably link to that section from "non-empty attributes", since it's not obvious that there's more to the syntax.

**Comment by eedahl** [comment]
I did look at it briefly, but it appears from the docs that id and class
are special cases and require static lifetimes, and the example uses this
as well so it's not quite clear to me what the possibilities/limitations
are. Ideally I'd be able to use run-time values, ifs etc. But I'll play
around with it!

**Comment by lfairy** [comment]
@eedahl The class and id shorthands are merely sugar around writing out the attributes in full. If they're generated dynamically, then it's okay to use the long form:

```rust
html! {
    tr id={ "lev-" (row.index) } {
        // ...
    }
}
```

Does this help?

**Comment by eedahl** [comment]
That does indeed change everything. From the documentation I got the
impression that classes and id's were determined statically only. I may
just be particularly slow, but adding an assurance to the documentation
that runtime code work on id and class tags may be worth doing!

**Comment by lfairy** [comment]
Closing in favor of #167
