### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by RalfJung** [lfairy/maud#131]
The documentation links both in the README and Cargo, pointing to https://docs.rs/maud/, is broken here: I get a mostly empty website saying "The requested resource does not exist".

**Comment by RalfJung** [comment]
That doesn't look completely correct either, e.g. the html macro reexport links to https://docs.rs/maud_macros/0.17.2/maud_macros/macro.%7B%7BGlobalMetaData::Krate%7D%7D.html which errors.

**Comment by lfairy** [comment]
I put out a new release and it [seems okay](https://docs.rs/maud/0.20.0/maud/). Closing as fixed.
