### ISSUE TITLE
Vue js incompatibility

### ISSUE THREAD

**Issue by max-frai** [lfairy/maud#134]
Hi, it's impossible to use vue.js with this library because there used custom attributes started with '@':
`<textarea :value="input" @input="update"></textarea>`
And maud think that is special keyword `input`.

Examples: https://vuejs.org/v2/examples/

**Comment by lfairy** [comment]
According to [this section](https://vuejs.org/v2/guide/syntax.html#Shorthands), that syntax is a shorthand. It should work if you write them out in full.

In general I don't want to bend over backwards to support this. Maud is a macro for writing HTML, not Vue.js 😛
