### ISSUE TITLE
Macro for DOCTYPE

### ISSUE THREAD

**Issue by kanarok** [lfairy/maud#147]
Currently I'm using (PreEscaped("\<!DOCTYPE html\>")) as the beginning of my markups.
Is there anything integrated with the same functionality? (I come close with DOCTYPE html?; All I'm missing is the exclamation mark)

**Comment by phansch** [comment]
You can use [DOCTYPE](https://docs.rs/maud/0.17.5/maud/constant.DOCTYPE.html) as in:

```rust
html! {
    (DOCTYPE)
    html {
        // ...
    }
}
```

**Comment by lfairy** [comment]
I'd like to keep this open as a docs issue, as the constant is a bit hard to find.

It's worth mentioning DOCTYPE somewhere in the book, perhaps the same place where PreEscaped is introduced.

**Comment by lfairy** [comment]
Documented in lfairy/maud-book@7c92c4d9a3a7cba6711d95fb445eb8f06bbf959a
