### ISSUE TITLE
Template separation

### ISSUE THREAD

**Issue by bhansconnect** [lfairy/maud#148]
This is just a question. Is there any good way to separate templates into different files?

Let's say that for example I have multiple templates and it is making my lib.rs file very long. 
With regular html templating, you would have a separate file for each template(each .html file).
With maud, the best way I can see to have a separate file for each template would be to build a module for every single template and each module would contain a single function that would be the template. Though this is functional, it ends up leading to strange imports like lib(library name)::hello(this is the module)::hello(this is the function).

**Comment by lfairy** [comment]
I tend to put everything in a single file myself.

But if you want to use separate files, you can `pub use` the functions from the parent module to get rid of the duplication (untested):

```rust
// src/views/mod.rs

#[path = "hello.rs"]
mod hello_module;

#[path = "world.rs"]
mod world_module;

pub use hello_module::hello;
pub use world_module::world;
```

```rust
// src/views/hello.rs

use maud::{html, Markup};

pub fn hello() -> Markup {
    html! {
        "Hello"
    }
}
```

```rust
// src/views/world.rs

use maud::{html, Markup};
use views::hello;

pub fn world() -> Markup {
    html! {
        (hello()) ", world!"
    }
}
```

Note that I renamed the modules (using `#[path]`) to avoid naming conflicts.

Does this help?

**Comment by bhansconnect** [comment]
That does help. Thanks.
