### ISSUE TITLE
Can't have single use renderables

### ISSUE THREAD

**Issue by Nemo157** [lfairy/maud#24]
Since `Render` takes itself by reference anything that implements it needs to support re-rendering multiple times. While working on supporting modified event streams in (second example at [`maud-pulldown-cmark`](https://git.nemo157.com/rust/maud-pulldown-cmark#example)) I found this limiting as `pulldown_cmark::Parser` isn't reusable, requiring me to wrap stuff up in closures to allow re-creating the parser when necessary. In most cases it's very unlikely that these structs would be kept around, so I was wondering if it were possible to have `fn render(self, w: &mut Write) -> fmt::Result` and provide implementations for references where needed.

**Comment by Nemo157** [comment]
To see whether this would work I attempted to implement it (https://git.nemo157.com/forks/maud/commit/f1ecd07). Took a while to work out how to get it working, but finally realised that emulating the `Fn`, `FnOnce` hierarchy would work, so in my code I could just `impl RenderOnce` and consume the `Parser` while rendering. If you want this I could open a pull request (+ `RenderMut` maybe, might be useful for some other advanced renderable?).

**Comment by Nemo157** [comment]
I threw together an implementation of `RenderMut` and some better tests for both [64565e8](https://git.nemo157.com/forks/maud/commit/64565e8).

**Comment by lfairy** [comment]
Cheers for the report. I agree that having a way to render a value by-move would be useful. But I'm hesitant about making that the default. After all, `println!("{}", x)` borrows `x` rather than moving it.

As for `RenderMut`: do you have a use case for this trait? I don't want to add it in unless there's a real use for it.

**Comment by Nemo157** [comment]
I can't think of any real use case for `RenderMut`. I just remembered that it will still default to borrowing a value if it implements `Render` because of the existence of `impl<'a, T: Render> RenderOnce for &'a T` and calling the method via `use ::maud::RenderOnce; $expr.render(&mut *$w)`. The compiler will auto-ref `$expr` till it finds the implementation of `RenderOnce` for `&$expr` then call that. I'll add a test that shows that in my changes for #26.
