### ISSUE TITLE
Alternative class/id syntax?

### ISSUE THREAD

**Issue by TheNeikos** [lfairy/maud#35]
Would it be possible to write something like this:

```rust
html! {
    .this-is-a-class#and_id {
        "Hello"
    }
}
```

Which would be a div with the class 'this-is-a-class' and the id 'and_id'. It would make writing a bit more ergonomic.

**Comment by lfairy** [comment]
Good idea!

There is already a shorthand for classes, but you do need to write out the tag name (e.g. `div.this-is-a-class`). This restriction is to avoid ambiguity: if you write something like `div .foo` it would be unclear whether you meant two nested `<div>`s or just one. See #28.

There's not yet a shorthand for IDs though, and I'd welcome a PR for that :)

**Comment by lfairy** [comment]
> There's not yet a shorthand for IDs though, and I'd welcome a PR for that :)

Never mind, I've implemented it myself :P

**Comment by TheNeikos** [comment]
Awesome! Thanks :D
