### ISSUE TITLE
Syntax error on double-dash in element class.

### ISSUE THREAD

**Issue by Fulkerson** [lfairy/maud#40]
Hello!

There seem to be an issue using class names with double dashes (--) when using the class shorthand:

`button.mdl-button--colored "Button"`

Results in:

    src/main.rs:110:34: 110:35 error: invalid syntax 
    src/main.rs:110                 button.mdl-button--colored "Button"
                                                     ^

I'm playing around with material design lite, and double dashes are frequently used in the CSS. See for example https://getmdl.io/started/index.html.

**Comment by lfairy** [comment]
Should be fixed in HEAD. Thanks for reporting!

**Comment by Fulkerson** [comment]
That was quick, it works fine now.

Thank you!
