### ISSUE TITLE
Allow for Structs to "wrap around content"

### ISSUE THREAD

**Issue by TheNeikos** [lfairy/maud#42]
I have a usecase that I believe would be rather awesome if it were implemented: Having a struct take content. It would be something like that:

```rust
html!(buffer, {
    !Column::new() {
        !Column::width_and_margin(10, 1) {
            h1 { "Hello World" }
        }
    }
});
```
Output:

```html
<div class="column-12">
    <div class="column-10 push-1">
        <h1>Hello World</h1>
    </div>
</div>
```

Where as Column would implement a trait that would emit a String or so, and get as an argument a reader which represents the content inside, something akin to:

```rust
pub trait Wrapper {
    fn wrap(&self, content: &Read) -> impl Write; 
}
```

--- 

I have seen that you have pushed something the past weeks that seems similar to that, if yes then it would be awesome to know how to use it and when it might be released.

**Comment by lfairy** [comment]
Good idea! I've been thinking of something similar lately, but hadn't come up with a compelling use case myself. But the motivation you put up sounds convincing.

The feature I pushed lets you run custom code in the middle of a template, yes, but it doesn't let you place additional markup in the middle. So I think what you're asking for is orthogonal.

I'm busy with work at the moment, so I'll give this idea a proper run through when I get the time.

**Comment by TheNeikos** [comment]
If you can spare some pointers I wouldn't mind diving into it and perhaps make something that could be used (or at least as base).

**Comment by lfairy** [comment]
@TheNeikos The relevant code is in `maud/src/lib.rs` (runtime) and `maud_macros/src/parse.rs` (syntax).

As for syntax, I suggest using something like

```rust
@with Column::new() {
   ...
}
```

The `@` suggests it's a special construct, and the word "with" (feel free to use another word instead) gives a slight hint as to what it does.

There's a [tiny bit of code](https://github.com/lfairy/maud/commit/cc370a35e58bf57bf2f58daac9d4824a320e6c75) you can build on. I imagine this syntax will compile to `.before()` and `.after()` calls using this trait.

**Comment by lfairy** [comment]
I also had another use case. If an app allowed the user to change e.g. CSS or JavaScript variables, this would necessitate another layer of escaping. So it would be cool if

```rust
let font_name = ... ;
html!(buffer, {
    p style={ "font-family: " @with css_string { (font_name) } } "Hello, world!"
})
```

applies CSS escaping rules in addition to the HTML escaping Maud performs by default.

I'm not sure about the role of the `PreEscaped` wrapper regarding this feature though, so it's okay if you don't implement this extra feature. Consider it a stretch goal :wink:

**Comment by lfairy** [comment]
I just realized: we don't have to add more syntax at all!

Right now, the `@call` syntax lets us pass the underlying writer to some custom closure. If we let this custom closure take *another* closure with markup in it, this will let us do some kind of nesting!

```rust
fn column<'a, T: Template + 'a>(inner: T) -> impl Template + 'a {
    template! {
        div.column-12 @call(inner)
    }
}

html!(buffer, @call(column(template! { "Hello, world!" })))
```

On the other hand, this `@call(foo(template! { ... }))` nesting can get tedious quickly. So I think now it would still be worth adding some kind of `@with` syntax, but with a different runtime interface. Something like this:

```rust
// not sure whether the lifetime parameter is necessary
pub trait Wrap<'a, T: Template + 'a> {
    type Wrapped: Template + 'a;
    fn wrap(inner: T) -> Self::Wrapped;
}
```

where `@with FOO { BAR }` desugars to `@call(FOO.wrap(template! { BAR }))`.

**Comment by lfairy** [comment]
Fixed in f12efe42995e88de443fec372154c12e86e5467c and released as Maud 0.11.

I've changed `html!` so that rather than taking a writer, it returns a `PreEscaped<String>` instead. With this new version, we can splice `html!` values together without needing any special syntax at all!

To bring it back to your example, a typical solution would look like this:

```rust
use maud::Markup;  // "Markup" is a type alias for "PreEscaped<String>"

fn column(inner: Markup) -> Markup {
    html! { div.column (inner) }
}

fn column_width_margin(width: u32, margin: u32, inner: Markup) -> Markup {
    // ...
}

html! {
    (column(html! {
        (column_width_margin(10, 1, html! {
            h1 "Hello, world!"
        }))
    }))
}
```

Another solution would be to write a builder struct that implements [`Render`](https://lambda.xyz/maud/maud/trait.Render.html).

Please tell me if you have any trouble using the new version!

**Comment by TheNeikos** [comment]
Okay that is a lot more elegant than what I thought of! 
Awesome! Will report back once I've used it.

**Comment by TheNeikos** [comment]
So I've been using this and incorporated it into my website, it works just as expected :+1:
