### ISSUE TITLE
Splices in class and ID names

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#45]
`h1#(foo)` should set the `id` attribute of `h1` to the value of `foo`. Similarly for `h1.(foo)`.

We'll have to think a bit about how to deal when `foo` is an iterable. Automatically add spaces between the elements?

**Comment by lfairy** [comment]
I'm not sure how useful this would be, considering that the logical extension `h1.foo-(bar)` won't work for the same reason as https://github.com/lfairy/maud/issues/44#issuecomment-259925114.

**Comment by TheNeikos** [comment]
I don't expect `h1.foo-(bar)` to work to be honest

**Comment by sackery** [comment]
保持以前的语法比较好

**Comment by lfairy** [comment]
@sackery Please use English. Most people here don't understand Chinese.

**Comment by sanmai-NL** [comment]
I also find this is very useful. I have a use case where I want the an (elaborate) HTML tag returned by a function to have a different class based on some logic.

**Comment by lfairy** [comment]
@sanmai-NL in your specific case, you can use `div.row.nav.special_nav[is_special] { ... }`

(I've filed #85 to document this feature.)

**Comment by lfairy** [comment]
Closing in favor of #128
