### ISSUE TITLE
(minor) Broken link in the Book

### ISSUE THREAD

**Issue by zofrex** [lfairy/maud#50]
The [FAQ page in the book](https://maud.lambda.xyz/faq.html) has a broken link to "[horrowshow](https://github.com/Stebalien/horrorshow)". From a quick Googling I think this may have moved to [horrowshow-rs](https://github.com/Stebalien/horrorshow-rs)?

Happy to PR, but you'll need to point me at the sources for the book as I couldn't find them :)

**Comment by lfairy** [comment]
Thanks for pointing that out! Should be fixed now.

The book's source is hosted on GitBook, so it's not publicly accessible at the moment. Though now you mention it, there is an option to use a GitHub repo instead. I'll look into it.
