### ISSUE TITLE
Support "while" and "while let"

### ISSUE THREAD

**Issue by sanmai-NL** [lfairy/maud#51]
I believe 
```rust
@while let ...
```
isn't supported currently (0.12.0). If not, it would be a welcome addition besides `@for` and `@if let`.

**Comment by lfairy** [comment]
I don't think plain `@while` is supported either.

I'll be happy to accept a PR for this. Should be easy to adapt from the code for `@if`.

**Comment by lfairy** [comment]
Don't worry about how I removed the "help wanted" label -- I still want help on this issue!

I just realized that since *all* issues here can be marked as "help wanted", the label itself is redundant :smile:

**Comment by sanmai-NL** [comment]
Great crate @lfairy, by the way! Keep it up. I appreciate the request for contribution, but I'm a Rust beginner and haven't even had time so far to do much with Rust. I'll have to see whether I can contribute to Maud at all.

I have been reconsidering my request in the meantime. I may not have this down correctly, but I think in all Rust versions up to today (< 1.15) `while` loops are r-values but must evaluate to `()`. Some have [petitioned](https://github.com/rust-lang/rfcs/issues/961) for this to be changed, though. Anyway, that means that the obvious `@while let` statement could not evaluate to e.g. a `maud::Markup` value. That means that unlike `@if` and `@for`, it is useless to have `@while let` inside `html! { ... }`. The alternative is to perform the while let outside of the `html!` { ... } and then use e.g. `@for` to pull out the `maud::Markup` values. What are your thoughts?

**Comment by lfairy** [comment]
@sanmai-NL I can see where you're coming from, but the fact that these Rust control structures return `()` is a red herring!

Maud doesn't care about what these control structures *return*. Instead, the body of an `@if` or `@for` pushes to an implicit buffer, and it is this buffer that is used as the resulting `Markup`. In other words: the structure itself always evaluates to `()` anyway; it's their side effects that we care about. So the RFC isn't relevant to this issue.

You can convince yourself that this is the case by playing around with [`html_debug!`](https://maud.lambda.xyz/debugging.html). `@while` should be expanded in much the same way as `@if` and `@for` are now.

**Comment by utkarshkukreti** [comment]
I'd like to give this a try if no one else is working on it.

**Comment by utkarshkukreti** [comment]
@sanmai-NL if you want, I'd be happy to submit a PR for this.
