### ISSUE TITLE
Change the `T: Display` constraint on `PreEscaped` to something else

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#54]
Using `Display` here seems wrong, because semantically `Display` gives a *plain text* representation, not an *HTML* representation. So in effect, `PreEscaped<T: Display>` is a claim that the plain text and HTML representations of a type are the same, which doesn't really make sense in general.

We can change the constraint to `T: AsRef<str>` instead. This covers what I think is the primary use case (including HTML output from an external source) without bringing in that semantic baggage. It doesn't cover fancy data structures like ropes, but I don't think they'll come up in a web app.

This change will also drive users toward implementing the `Render` trait, which is the idiomatic way to customize HTML output (see #53).

**My question is:** Are there any existing use cases of `PreEscaped` which are not either...

1. Including HTML output from an external source (e.g. a blog post converted from Markdown)

2. `PreEscaped("<!DOCTYPE html>")`

3. Anything which is better written using the `Render` trait instead

... ?

If not, then we can go ahead on this change.

**Comment by TheNeikos** [comment]
Why not constrain on `Render` and remove the Blanket impl for `Display` ?

**Comment by TheNeikos** [comment]
This would entail implementing it for all the primitives, but I guess it's feasible (with a macro it should be simple too)

**Comment by lfairy** [comment]
@TheNeikos That is an interesting idea. I've mulled over the issue a bit, and I think the blanket `impl<T: Display> Render for T` is still useful.

For many types (e.g. [`IpAddr`](https://doc.rust-lang.org/std/net/enum.IpAddr.html), [`Version`](https://docs.rs/semver/0.5.1/semver/struct.Version.html), [`Url`](https://docs.rs/url/1.2.2/url/struct.Url.html)...) we do want to re-use the `Display` impl. It'd be annoying to write `Render` instances for all of these.

I also don't think the same argument works for `PreEscaped<T>`. If you know that an IP address never contains a special character, then the best way to show that is by specializing the `Render` impl. Not by asking everyone who uses IP addresses to wrap them in `PreEscaped` 😜

Given these points, I'm going ahead with the original plan.
