### ISSUE TITLE
Toggle the presence of an attribute using Option<T>

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#58]
# Alternative 1

```rust
let surprise = Some("Boo!");
html! {
    p title?=(surprise) "Hover over me"
}
```

# Alternative 2

Like Alternative 1, but with the syntax `title=?(surprise)` instead.

# Alternative 3

Use the same syntax as normal splices, `title=(surprise)`, but use trait magic to omit the attribute when `surprise.is_none()`.

Implementation: Add a method, `fn is_present(&self) -> bool`, to the `Render` trait. This method returns `true` for all types except `Option<T>`, which returns `self.is_some()`. Then at run time, the code will call `surprise.is_present()` to decide whether or not to emit the attribute.

Not sure how this composes -- what does `title={ "I say: " (surprise) }` mean?

**Comment by lfairy** [comment]
After filing #59, I came up with another alternative: `p title=(surprise)?`.

**Comment by lfairy** [comment]
Looking at this again, I'm not sure what use case I have for this feature. So I'm closing it for now.

If you have a use for this, feel free to make a comment!

**Comment by Korvox** [comment]
I ran into something that could use this. I have a dataset I want to prefill a form with, but the sourcing of that data isn't uniform or guaranteed so it is all optional. If I could write it like this:

```rust
html! {
   input type="text" value?=(data.value);
}
```
It would be much more ergonomic than how I have it written now which looks like this:

```rust
html! {
    input type="text" value=({ if let Some(s) = data.value { s } else { "" }});
}
```
It would also be nice because right now there is no way (I think?) to have an attribute that either exists with a value or doesn't exist with no value without doing conditionals on the entire element.

**Comment by lfairy** [comment]
@Korvox you can make that shorter with a wrapper struct:

```rust
struct Optional<T>(Option<T>);

impl<T: Render> Render for Optional<T> {
    fn render_to(&self, buffer: &mut String) {
        if let Some(ref value) = self.0 {
            value.render_to(buffer);
        }
    }
}
```

Does that help?

---

By the way: there's no difference between an empty `value` and a missing one [as far as I can tell](https://html.spec.whatwg.org/multipage/input.html#attr-input-value).

The only case I know of where a missing and empty attribute have different meanings is [the `alt` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt). An empty `alt` says that the image has *no* meaning, but a missing `alt` says that the image has an *unknown* meaning.

I haven't looked very hard though, so there might be others I've missed.
