### ISSUE TITLE
Macros/Partials collection

### ISSUE THREAD

**Issue by ernestas-poskus** [lfairy/maud#64]
Hi, first of all thank you for great feeling that this crate gives. I have accumulated number of partials for maud for various repeating elements. I would like to share/open source them. I wonder whether you could create new repository something like maud_elements or alike. My point is it would be good to keep everything in one place where everyone could reuse or add new partials.

**Comment by lfairy** [comment]
That sounds like a great idea!

I'm not sure what the convention is for a single "extras" crate, though. It doesn't seem right to group unrelated things together -- if someone wants just a single feature, they shouldn't need to bring in everything else with it.

What are some of the partials you've written so far? We might get a clearer picture with some concrete examples.

**Comment by ernestas-poskus** [comment]
Like generation of meta tags, html charset, open graph tags and other goodies 

```
use maud::Render;

pub struct Tags {
    pub title: &'static str,
    pub description: &'static str,
}

impl Render for Tags {
    fn render_to(&self, f: &mut String) {
        f.push_str(&html!(
            title { (self.title) }
            meta property=("description") name=("description") content=(self.description) /
        ).into_string())
    }
}
```

**Comment by lfairy** [comment]
I've created a new [maud_extras](https://github.com/lfairy/maud/tree/master/maud_extras) crate. Feel free to make a PR there!

**Comment by TheNeikos** [comment]
I have some reusable components that I already created for my project: https://github.com/TheNeikos/furry.cafe/tree/master/src/views/components

If someone feels like pilfering them and re-factor them for here or so feel free.
