### ISSUE TITLE
RFC: Remove the RenderOnce trait

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#68]
After getting more experience with the library, I've found it hard to justify having this trait. I've never seen real-world code that uses it; I had to jump through hoops to make up an example for [the book](https://maud.lambda.xyz/traits.html). (The [snippet that it's based on](https://github.com/lfairy/karkinos/blob/040abfbfa3b9579d15d4db218d8ef7b21c2dc0aa/src/views.rs#L243-L264) takes a different approach entirely.)

When it was first added, the `RenderOnce` trait was supposed to allow for easier streaming. For example, we could write a wrapper that streams rows from a database query, and renders then one-by-one to the client. But since version 0.11 removed both streaming and error handling, this use case no longer applies.

Removing `RenderOnce` would mean one less concept to learn, and remove any confusion about which trait to use. If it's really needed, then we can fake linearity with [`MoveCell`](https://crates.io/crates/movecell).

Pinging @Nemo157 since they introduced the trait, and @TheNeikos since they use the library.

**Comment by Nemo157** [comment]
Taking a look at [Nemo157/grarr][] I never actually ended up using the event based markdown rendering that needed `RenderOnce`, only ever rendering from a string.

[TheNeikos/furry.cafe][] is the only other place I can find using `maud-pulldown-cmark`, it is using the event based rendering though.

I just came up with an alternative design that would allow the usage furry.cafe requires from it without the `RenderOnce` trait, take in a string + a closure to modify the event stream and create the event stream as needed. I'm happy to make that change if you kill off `RenderOnce`.

[Nemo157/grarr]: https://github.com/Nemo157/grarr
[TheNeikos/furry.cafe]: https://github.com/TheNeikos/furry.cafe/blob/ec51f70d62fcffb7e9911a3a401e1364be39e881/src/views/markdown.rs

**Comment by TheNeikos** [comment]
I don't mind changing my usage. I'm all for simplifying things, especially if it's not really used. (I just went with what existed, I *didn't* want to think about how to implement Markdown)

**Comment by lfairy** [comment]
Okay -- since nobody's objected in the mean time, I've gone ahead and removed the trait. Thanks @Nemo157 and @TheNeikos for your comments!
