### ISSUE TITLE
This has 0.1.1 but crates.io has 0.1.2?

### ISSUE THREAD

**Issue by oderwat** [lfairy/maud#7]
I just saw your update here and wondered, because it already compiled for me since some time. Now I saw that the github version has 0.1.1 in toml but the cargo.io version is 0.1.2 since 30. january :)

What is going on here? Time machine?

**Comment by lfairy** [comment]
v0.1.2 is here: https://github.com/lfairy/maud/tree/v0.1.2

The relevant bug (#6) was reported after I'd already landed a few breaking changes on master. So instead of rushing to polish up all those changes, I decided to branch off v0.1.1 and cherry-pick the fix instead.
