### ISSUE TITLE
Missing fields `close_span`, `open_span` in initializer of `syntax::tokenstream::Delimited`

### ISSUE THREAD

**Issue by Frederick888** [lfairy/maud#71]
I'm getting this error with `rustc 1.16.0-nightly` and `maud 0.15.0`.

```
   Compiling maud_macros v0.15.0
/home/frederick/.cargo/registry/src/github.com-1ecc6299db9ec823/maud_macros-0.15.0/src/parse.rs:418:52: error: E0063: missing fields `close_span`, `open_span` in initializer of `syntax::tokenstream::Delimited`
error: Could not compile `maud_macros`.
```

Modifying `parse.rs:418` back to
```
body.push(TokenTree::Delimited(sp, Rc::new(Delimited {
    delim: DelimToken::Brace,
    open_span: sp,
    tts: expr,
    close_span: sp,
})));
```
fixes the issue.

**Comment by lfairy** [comment]
Is your compiler up-to-date? It builds successfully with `rustc 1.16.0-nightly (df8debf6d 2017-01-25)`, and as far as I know that's the latest one.

**Comment by Frederick888** [comment]
@lfairy Yes you were right. I should have checked compiler updates first. Thanks for your quick response.
