### ISSUE TITLE
Document `({ /* arbitrary Rust code */ })`

### ISSUE THREAD

**Issue by trombonehero** [lfairy/maud#72]
I wasn't able to find anything in the Maud documentation about the fact that splices can contain arbitrary Rust code, including compound expressions. I did stumble on #11, which contains a comment referencing `${ ... }` before I created a bug about type inference, but it would be useful if the documentation had an example of this kind of thing. For instance:

```rust
p ({
  let user:User = try![database.lookup(userid)];
  user.name
})
```

This is also an example of the kind of thing that can fail when using Maud `@let` directives: they don't accept type annotations, so I sometimes get "the type of this value must be known in this context" errors.

**Comment by sackery** [comment]
You can use
```rust
@let ...;
@if let...;
```

**Comment by sackery** [comment]
This style I supported but refused.
```rust
@ {
   // Arbitrary code here.
}
```

**Comment by lfairy** [comment]
The documentation can be found at https://github.com/lfairy/maud-book. I'm too swamped with work at the moment to edit it myself, but if you have the time then I'd welcome a pull request.

I think `@let` not supporting type annotations is a bug. I've filed that as #73.

**Comment by trombonehero** [comment]
Thanks! I've created lfairy/maud-book#1.

**Comment by lfairy** [comment]
I believe @trombonehero's PR closes this issue.
