### ISSUE TITLE
`@let` and `@for` should support type annotations

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#73]
The following syntax should work, but doesn't:

```rust
html! {
    @let foo: Bar = baz() {
        // ...
    }
}
```

See #72.

**Comment by trombonehero** [comment]
The same is probably true of `@for` as well, e.g.:

```rust
@for u: User in self.0.as_ref() {
    tr {
        td (u.name)
        td (u.email)
        /* ... */
    }
}
```

**Comment by lfairy** [comment]
The following code works on master:

```rust
#[test]
fn let_type_ascription() {
    let s = html! {
        @let mut x: Box<Iterator<Item=u32>> = Box::new(vec![42].into_iter()) {
            "I have " (x) " cupcakes!"
        }
    }.into_string();
    assert_eq!(s, "I have 42 cupcakes!");
}
```

I have added this as a test in 4a733993c8efd95f51b57786035536ae672f5bfb.

Type ascription in `for` patterns [isn't supported in Rust proper](https://play.rust-lang.org/?gist=158f7b95f037c5a0733f09cb5ca40d24&version=stable), so I'll consider that a wontfix. See rust-lang/rfcs#354.
