### ISSUE TITLE
Rocket Responder not working with v0.2.0?

### ISSUE THREAD

**Issue by trombonehero** [lfairy/maud#76]
I'm using Maud v0.16.1 and attempting to update Rocket from v0.1.6 to v0.2.0. The following reduced test case works fine with Rocket v0.1.6:

```rust
use rocket::response;
use rocket::response::{Responder, Response};

pub enum Foo {}

impl<'r> Responder<'r> for Foo {
    fn respond(self) -> response::Result<'r> {
        (html! {}).respond()
    }
}
```

With Rocket v0.2.0, however, I see:

```
error: no method named `respond` found for type `maud::PreEscaped<std::string::String>` in the current scope
 --> src/html/abc.rs:8:20
  |
8 |         (html! {}).respond()
  |                    ^^^^^^^
  |
  = help: items from traits can only be used if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
  = help: candidate #1: `use rocket::response::responder::Responder;`

error: aborting due to previous error
```

The `rocket::response::responder` module is private, however, so I can't `use` it as suggested. I do see a `respond()` method at [Maud's lib.rs:212](https://github.com/lfairy/maud/blob/master/maud/src/lib.rs#L212) and I have `features = ["rocket"]` in my Cargo.toml file. Any idea why Maud's `impl Responder for PreEscaped` isn't being detected?

**Comment by lfairy** [comment]
Can you show me the contents of your `Cargo.lock`? That looks like a diamond dependency issue -- if your app uses 0.2.0 but Maud is still pulling in 0.1.6, then that would explain the error.

**Comment by trombonehero** [comment]
Ah, yes, that was it: there was a `0.1.6` in `Cargo.lock`. Deleting the lock file and rebuilding did the trick. Sorry for the noise.

**Comment by lfairy** [comment]
FYI, the issues rust-lang/rust#22750 and rust-lang/cargo#2064 address both sides of this issue. I don't see much movement with either of them, though.

**Comment by TheNeikos** [comment]
@trombonehero Deleting your Cargo.lock shouldn't be necessary, `cargo update` should have been enough in that case I believe (also with `--precise`)
