### ISSUE TITLE
Remove `error!` macro

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#84]
See https://github.com/lfairy/maud/blob/be88fc39d5d56370d3db020ef85f4f093ab45a60/maud_macros/src/parse.rs#L14-L19

This should really be a method on `Parser` instead.

Tasks:

- [ ] Add a `Parser::error()` method with a similar signature to the `error!()` macro
- [ ] Change all instances of `error!(...)` to `return self.error(...)`
- [ ] Remove the `error!()` macro

**Comment by alisha17** [comment]
I am working on this issue!
