### ISSUE TITLE
Document toggled classes

### ISSUE THREAD

**Issue by lfairy** [lfairy/maud#85]
```rust
let is_cute = true;
html! {
    p.cute[is_cute] {
        // ...
   }
}
```

Should go in https://github.com/lfairy/maud-book/blob/master/basic_syntax.md under the "classes and IDs" section.

**Comment by DeltaManiac** [comment]
I'll be happy to work on this.
Would this just be adding change like below ?

## Classes and IDs `.foo` `#bar`

```rust
html! {
    div.container#main {
        input.big.scary.bright-red type="button" value="Launch Party Cannon" /
    }
}
```
Add classes and IDs to an element using `.foo` and `#bar` syntax. You can chain multiple classes and IDs together, and mix and match them with other attributes.

```Rust
let is_cute = true;
html! {
    p.cute[is_cute] {
        // ...
   }
}
```
Rust bindings can be used in coherence with html elements to set their attrubutes.

**Comment by lfairy** [comment]
@DeltaManiac I think that's the right idea.

I wouldn't use words like "bindings" or "coherence" here, though. There are simpler words that mean the same thing.

I recommend using similar wording to the [empty attributes section](https://github.com/lfairy/maud-book/blob/master/basic_syntax.md#empty-attributes-checked-disabledfoo), since that feature works in much the same way.

**Comment by sanmai-NL** [comment]
Uhm, sorry, hadn't noticed @DeltaManiac's announcement! I filed a PR already.

**Comment by DeltaManiac** [comment]
@sanmai-NL 
No issues ! 👍
