### ISSUE TITLE
Compatibility with rust 1.0.0

### ISSUE THREAD

**Issue by niclashoyer** [lfairy/maud#9]
I know that the introduction clearly states that

> You'll need to install the Nightly version of Rust to use it.

But it would be nice if there was a hint at what compiler APIs are required and when they are going to be stable.

**Comment by lfairy** [comment]
I reworded it to say

> Maud depends on the [syntax extension API](https://doc.rust-lang.org/book/compiler-plugins.html)

instead, which should be enough.

Nobody knows when the relevant APIs will be stable, so I'm not going to cover that.

**Comment by niclashoyer** [comment]
thank you!
